Turtle has egg trait
Nathat23/StackMob-5 pull request #188
Opened 2021-02-15 11:39 UTC by HauserGrim

Prevent stacking pregnant turtles

2021-02-15 11:42 UTC, Aurelien30000 requested changes

2021-02-15 11:42 UTC, Aurelien30000 commented on src/main/resources/config.yml
> +  # Paper
Remove this comment and follow the conventions at the beggining of the file :D ``# (**)`` comment

2021-02-15 18:36 UTC, Aurelien30000 approved these changes

2021-02-16 21:38 UTC, Nathat23 commented on src/main/resources/config.yml
> +  # (**)
It would be better to describe what the config path does, since its not obvious.

2021-02-19 10:40 UTC, merged